### ISSUE TITLE
Quizzes

### ISSUE THREAD

**Issue by shiffman** [ITPNYU/ICM-2016#4]
We discussed publishing short, simple "quizzes" that the students can self-administer to check their knowledge.    Should we have one for each week?  One quiz that covers all fundamentals (week 1-5)?  I created a draft quiz for week 1.

https://github.com/ITPNYU/ICM-2016/wiki/Quiz-1

**Comment by mimiyin** [comment]
I like how #4 (Draw a line from the top right to bottom left of the canvas.) is framed as problem-solving (applying recalled information to a goal) as opposed to straight recall.

So #3 could be: What numbers do you need to plug into fill() to get a bright turquoise? 
Online Color Picker: http://www.w3schools.com/colors/colors_picker.asp

So it might be better to wait until the students are playing with variables to test setup() and draw().

**Comment by shiffman** [comment]
I moved the quizzes to here:

https://github.com/shiffman/ICM-Quizzes
http://shiffman.github.io/ICM-Quizzes/week1-drawing/

**Comment by shiffman** [comment]
These are in progress I'm trying to keep up and make one each week, closing.
